{ //variaveis
var versao = "Version: 1.0 95 BETA";
var nome = 'KoGaMa Blendox 95 BETA';
var namespace = 'Null';
var uvar = 'Usos de var: ' + Uvar;
var ulet = 'usos de let: ' + Ulet;
var Ulet = 0
var Uvar = 4
var description = 'Versão considerada "versão de testes"';
var author = 'Blendox©';
var author2 = 'Android';
var stade = 'Manutenção';
var helper = 'Henry Pierre';
var errorfixer = 'Lighty_Walskkyy_Wonder_Storm';
}
{ //variaveis
var versao = "Version: Test";
var nome = 'KoGaMa Blendox  BETA';
var namespace = 'Null';
var uvar = 'Usos de var: ' + Uvar;
var ulet = 'usos de let: ' + Ulet;
var Ulet = 0
var Uvar = 4
var description = 'Versão considerada "versão de testes"';
var author = 'Blendox©';
var author2 = 'Android';
var stade = 'Manutenção';
var helper = 'Henry Pierre';
var errorfixer = 'Lighty_Walskkyy_Wonder_Storm';
}
window.alert ('Carregamento Completo. Feito por android e HenryPierre');
